### ISSUE TITLE
Bidirectional examples does not work on dev branch

### ISSUE THREAD

**Issue by st0rrer** [koorchik/node-mole-rpc-transport-ws#3]
Caught execption when call client method from server
RequestTimout [Error]: Request exceeded maximum execution time
    at Timeout._onTimeout (/home/st0rrer/workspace/st0rrer/json-rpc/node-mole-rpc-transport-ws/node_modules/mole-rpc/MoleClient.js:71:28)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: -32001,
  message: 'Request exceeded maximum execution time'
}

**Comment by koorchik** [comment]
master branch has a lot of small improvements. Close this issue, as dev branch will be deleted.
